const actionTypes = {
  INIT_SHOP_PAGE: 'INIT_SHOP_PAGE',
  SHOP_PAGE_DATA_FETCHED: 'SHOP_PAGE_DATA_FETCHED',

  BUY_SUBMIT: 'BUY_SUBMIT',
  BUY_ERROR: 'BUY_ERROR',
  BUY_SUCCESS: 'BUY_SUCCESS',

  NEW_COMMENT_SUBMIT: 'NEW_COMMENT_SUBMIT',
  NEW_COMMENT_ERROR: 'NEW_COMMENT_ERROR',
  NEW_COMMENT_SUCCESS: 'NEW_COMMENT_SUCCESS',
};

export default actionTypes;
